### ISSUE TITLE
RemNote Library Report: Rem Type and Practice Direction v1.2.1

### ISSUE THREAD

**Issue by MyEnthusiastic** [hannesfrank/remnote-css-rem-types#5]
**Please check first if there is an update of this scroll available.**---- **Id:** com.github.hannesfrank.remnote-css-rem-types- **Version:** 1.2.1- **Type:** Problem/Suggestion (choose one)- [ ] Describe the problem you are having with the scroll or how it should be improved.- [ ] _Add_ a short description to the title (don't replace it completely!) so people know what this is about.- [ ] Make sure to include a screenshot or image to make your issue easy to understand.---
It mess up with the direction: when it shoud be "forward only", it desplays both sides
![image](https://user-images.githubusercontent.com/54618402/122877262-0000a080-d369-11eb-8eb9-fe59d59fc5cb.png)
Here is my current version, PC desktop
![image](https://user-images.githubusercontent.com/54618402/122877438-30483f00-d369-11eb-953c-7ff2e03bec96.png)

**Comment by hannesfrank** [comment]
Thanks for the report @mynameisenthusiasm! This was due to a recent renaming of the variable names. I pushed the updated version to the library now.

Note the variable names in the Customization section do not match the arrows:
![image](https://user-images.githubusercontent.com/4137110/122880557-6a4e1c80-d33a-11eb-89da-12a92e49c0bb.png)

Please update the scroll to v1.2.2 by "reinstalling" it (delete the old and paste the new) or fix the arrow icons in the `Customization` section yourself.
